In [1]:
import numpy as np
from sys import getsizeof as size

<h1 style="color:orange">shape, dtype, order</h1>

* Shape: tuple of array dimensions 2D (rows,columns) ex===> (4*3)
* dtype: create a data type object
* order: column-major (Fortran), row-major (C)

<h1 style="color:orange">Array creation routines</h1>


In [2]:
# empty(shape[, dtype, order]) Return new array of given shape and type, without initializing entries(random data).

np.empty(5)
np.empty(5,dtype = np.int8)
np.empty([2,3],dtype = np.int8)

# empty_like(prototype[, dtype, order, subok]) Return new array with same shape and type, as a given array.
prototype = (range(0,10),range(0,10))
np.empty_like(prototype,dtype = np.int8)

array([[ 64,  24,  61, -18,  -1,  85,   0,   0,   0,   0],
       [  0,   0,   0,   0,   0,   0, -16,  55, -63, 122]], dtype=int8)

In [3]:
# eye(n[,m, k, dtype, order]) Return 2d array with ones on the diagonal(ghotr asli) and zero elsewhere.
np.eye(5)
np.eye(3,4)
np.eye(3,4,k=1)
np.eye(3,4,k=-2)
np.eye(5,5)


array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [4]:
# identity(n[, dtype]) Return identity array with ones on the diagonal(ghotr asli) and zero elsewhere.
np.identity(10)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [5]:
# ones(shape[, dtype, order]) Return new array of ones .
prototype = np.eye(5)

np.ones(10)
np.ones((4,8))
np.ones_like(prototype)

np.zeros((4,8))
arr = np.zeros_like(prototype,dtype=np.int8)

arr.shape
arr.dtype
arr.ndim #abaad => nD

2

In [6]:
# full(shape, full_value[, dtype, order]) Return new array of given value .
prototype = np.eye(5)

np.full(10,6)
np.full((3,8),6)

np.full_like(prototype,6)
np.full_like(prototype,6,dtype=np.int8)


array([[6, 6, 6, 6, 6],
       [6, 6, 6, 6, 6],
       [6, 6, 6, 6, 6],
       [6, 6, 6, 6, 6],
       [6, 6, 6, 6, 6]], dtype=int8)

In [7]:
# numpy.array(object, dtype=None, *, copy=True, order='K', subok=False, ndmin=0, like=None)

scores = np.array([10,15,16,18])
np_scores1 = np.array(scores,copy=False)
np_scores1[1] = 20

np_scores2 = np.array(scores,dtype=np.int8,copy=False)
np_scores2[1] = 20

scores

array([10, 20, 16, 18])

In [8]:
# numpy.matrix(data, dtype=None, copy=True)
mat = np.matrix([[10,20,30]])
arr = np.array(mat, copy=False)
arr[0][2] = 40
print(mat)

arr is mat # False
id(arr) == id(mat) # False
np.may_share_memory(arr,mat) # True

np.array(mat, copy=False, subok=True) is mat

[[10 20 40]]


True

In [9]:
# numpy.asarray(a, dtype=None, order=None, *, like=None) ==> copy is False
# numpy.asanyarray(a, dtype=None, order=None, *, like=None) ==> copy=False, subok=True

In [10]:
# numpy.ascontiguousarray(a, dtype=None, *, like=None) Return a contiguous array (ndim >= 1) in memory (C order).

x = np.arange(10).reshape(2,5,order='f')
x = np.ascontiguousarray(x)

x.shape
x.flags

# x
# id(x) == id(y) # True
# np.may_share_memory(x,y) # True

  C_CONTIGUOUS : True
  F_CONTIGUOUS : False
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False
  UPDATEIFCOPY : False

In [11]:
# numpy.asmatrix(data, dtype=None)[source] Interpret the input as a matrix.
#Unlike matrix, asmatrix does not make a copy if the input is already a matrix or an ndarray. 

In [12]:
# numpy.copy(a, order='K', subok=False)[source] Return an array copy of the given object.
# nupmpy copy is shalow copy
# for deep copy import copy

a = np.array([1,'masoud',[4,5,6]], dtype=object)
b = np.copy(a)

b[2][0] = 500


#-----------------
from copy import deepcopy
b = deepcopy(a)
b[2][0] = 200



print(a,b)

[1 'masoud' list([500, 5, 6])] [1 'masoud' list([200, 5, 6])]


In [13]:
# numpy.frombuffer(buffer, dtype=float, count=- 1, offset=0, *, like=None)
# Interpret a buffer as a 1-dimensional array.

string = b'masoud'
np.frombuffer(string, dtype='S1')
np.frombuffer(string, dtype='S1', count=2)
np.frombuffer(string, dtype='S1', offset=2)

array([b's', b'o', b'u', b'd'], dtype='|S1')

In [14]:
# numpy.fromfunction(function, shape, *, dtype=<class 'float'>, like=None, **kwargs)[source]
# Construct an array by executing a function over each coordinate.
# The resulting array therefore has a value fn(x, y, z) at coordinate (x, y, z).

np.fromfunction(lambda i,j : i==j, (3,3), dtype=np.int8)


array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [15]:
# numpy.fromiter(iter, dtype, count=- 1, *, like=None)
# Create a new 1-dimensional array from an iterable object.
    
np.fromiter([i/3 for i in np.empty(10,dtype = np.int8) ], dtype=np.int8)

array([10, 19, 22, -6,  0, 28,  0,  0,  0,  0], dtype=int8)

In [16]:
# numpy.fromstring(string, dtype=float, count=- 1, *, sep, like=None)
# A new 1-D array initialized from text data in a string.

string= '2,121,123,54,2'
np.fromstring(string, sep=',', dtype=np.int8)



array([  2, 121, 123,  54,   2], dtype=int8)

In [17]:
# numpy.loadtxt(
#               fname, dtype=<class 'float'>, comments='#', delimiter=None, converters=None, 
#               skiprows=0, usecols=None, unpack=False, ndmin=0, encoding='bytes', max_rows=None, *,
#               quotechar=None, like=None
#              )

def correct_height(h):
    try:
        return float(h)
    except ValueError:
        return -1000.
    


dtype1 = np.dtype([('Sex','S1'),('Age','f8')])
file_name = '../../datasets/titanic.csv'

# np.loadtxt(file_name, dtype=dtype1, skiprows=9, usecols=(4,5), converters={4:correct_height})

In [18]:
import pandas as pd
titanic_data = pd.read_csv(file_name)
male = titanic_data[['Sex','Age']]
male[male['Sex']=='male']['Age'].mean(skipna =True)


30.72664459161148