In [1]:
import numpy as np

In [2]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
arr[5:8] = -100
arr

array([   0,    1,    2,    3,    4, -100, -100, -100,    8,    9])

In [4]:
arrslice = arr[2:5] # whene slice its by refrence
arrslice[0] = 20
arr

array([   0,    1,   20,    3,    4, -100, -100, -100,    8,    9])

In [5]:
arrsliceCopy = arr[2:5].copy()
arrsliceCopy[0] = 50
arr

array([   0,    1,   20,    3,    4, -100, -100, -100,    8,    9])

In [6]:
arr[:] = 100
arr

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [7]:
arr2d = np.arange(1,10).reshape(3,3)
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [8]:
arr2d[0][2] == arr2d[0,2]

True

In [9]:
arr2d[:2,:2]

array([[1, 2],
       [4, 5]])

In [10]:
arr3d = np.arange(1,13).reshape(2,2,3)
print(arr3d)
arr3d[0,1,1]

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


5

In [64]:
#boolean indexing Return a copy

names = np.array(['masoud','mostafa','younes','masoud','mostafa','mohammad','masoud'])
data = np.random.randn(7,4)

newData = data[~ (names=='masoud'),:1]

print(data)
newData[0] =10
print(newData)
data


[[ 1.71694751 -1.42652587  2.09838972  0.52116319]
 [-0.89782317 -1.03455285 -1.28818293  1.1339785 ]
 [-1.13482642  0.37185198 -0.42277486  1.12245502]
 [ 0.85501923 -0.80778169 -0.119193   -1.18727206]
 [ 0.01190236 -0.65656037 -0.26439578 -0.26694751]
 [ 0.43688298 -0.01754592  0.74715314 -1.19691616]
 [ 0.41040376 -1.27051089  1.03168654  0.51407306]]
[[10.        ]
 [-1.13482642]
 [ 0.01190236]
 [ 0.43688298]]


array([[ 1.71694751, -1.42652587,  2.09838972,  0.52116319],
       [-0.89782317, -1.03455285, -1.28818293,  1.1339785 ],
       [-1.13482642,  0.37185198, -0.42277486,  1.12245502],
       [ 0.85501923, -0.80778169, -0.119193  , -1.18727206],
       [ 0.01190236, -0.65656037, -0.26439578, -0.26694751],
       [ 0.43688298, -0.01754592,  0.74715314, -1.19691616],
       [ 0.41040376, -1.27051089,  1.03168654,  0.51407306]])

In [95]:
# Fancy indexing ===> select custom row and insert in new array
arr = np.arange(12).reshape(4,3)
print(arr,'\n')
print(arr[[3,2]])


arr[[2,3],[1,2]]

# read for more and 2d fancy indexing

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]] 

[[ 9 10 11]
 [ 6  7  8]]


array([ 7, 11])