In [1]:
import numpy as np

In [66]:
# numpy.argmax(a, axis=None, out=None, *, keepdims=<no value>) Rturns the indices of the maximum values
# numpy.nanargmax(a, axis=None, out=None, *, keepdims=<no value>)
# Return the indices of the maximum values in the specified axis ignoring NaNs. For all-NaN slices ValueError is raised. Warning: the results cannot be trusted if a slice contains only NaNs and -Infs.

# numpy.argmin(a, axis=None, out=None, *, keepdims=<no value>)Returns the indices of the minimum values along an axis.
# numpy.nanargmin(a, axis=None, out=None, *, keepdims=<no value>)

arr = np.random.randint(16 , size=(4,4))
print(arr,'\n')

print( np.argmax(arr,axis=-1))
# print( np.argmax(arr,axis=1))
 
index_array = np.argmax(arr,axis=-1)
value_array = np.take_along_axis(arr, np.expand_dims(index_array, axis=-1), axis=-1)
value_array

[[ 2 15 10  6]
 [ 5 15  1  9]
 [ 0 10 15  0]
 [ 8  3 12  9]] 

[1 1 2 2]


array([[15],
       [15],
       [15],
       [12]])

In [131]:
# numpy.where(condition, [x, y, ]/) Return elements chosen from x or y depending on condition.
bloodPresure = np.array([10,11,12,16,18,13,14,15])
low = ['L','L','L','L','L','L','L','L']
high = ['H','H','H','H','H','H','H','H',]
# np.where(bloodPresure>12,high,low)


arr2 = np.random.randint(16 , size=(4,4))
print(arr2)
arr2[np.where(arr2>3)]


[[3 1 0 0]
 [1 4 0 3]
 [4 2 1 4]
 [2 1 0 2]]


array([4, 4, 4])

In [188]:
# numpy.argwhere(a) Find the indices of array elements that are non-zero, grouped by element.
arr2 = np.array([[0 ,0 ,0, 1],[2, 3, 4, 1],[0, 1, 2, 4],[3, 3, 2, 4] ])
print(arr2)

np.argwhere(arr2) 
np.argwhere(arr2>3) 


[[0 0 0 1]
 [2 3 4 1]
 [0 1 2 4]
 [3 3 2 4]]


array([[1, 2],
       [2, 3],
       [3, 3]])

In [192]:
# numpy.nonzero(a) Return the indices of the elements that are non-zero.
arr2 = np.array([[0 ,0 ,0, 1],[2, 3, 4, 1],[0, 1, 2, 4],[3, 3, 2, 4] ])

print(np.nonzero(arr2>3))

(array([1, 2, 3]), array([2, 3, 3]))


In [225]:
# numpy.extract(condition, arr) Return the elements of an array that satisfy some condition.
arr2 = np.array([[0 ,0 ,0, 1],[2, 3, 4, 1],[0, 1, 2, 4],[3, 3, 2, 4] ])

np.extract(arr2-2>1,arr2)
np.extract(np.mod(arr2,4)!=0,arr2)



array([1, 2, 3, 1, 1, 2, 3, 3, 2])