In [1]:
import numpy as np

<h1 style='color:orange'>Array Operation</h1>

In [69]:
x = np.array([1,2,3])
y = np.array([1,0,-1])

x+y
x-y
x*y # multiply , element by element
y/x
y//x
x**2

np.dot(x,y) # zarb matrisi
x@y # zarb matrisi


-2

In [58]:
a = np.arange(1,5).reshape(2,2)
b = np.arange(10,14).reshape(2,2)
print(a,'\n----\n',b,'\n----\n')

a+b
a*b
np.dot(a,b)

[[1 2]
 [3 4]] 
----
 [[10 11]
 [12 13]] 
----



array([[34, 37],
       [78, 85]])

<h1 style='color:orange'>Broadcasting</h1>

<h1 style='color:orange'>Random Number Generators</h1>

In [200]:
np.random.rand() # uniform random number
np.random.rand(10)
np.random.rand(2,3)

#---------------------------------------------------
np.random.randn() # normal random number
np.random.randn(10)
np.random.rand(2,3)
#---------------------------------------------------
np.random.randint(-10,10)
np.random.randint(-10,10, (2,3))



array([[-10,   2,  -3],
       [ -3,   3,  -9]])

<h1 style='color:orange'>Optimization</h1>

In [218]:
np.linspace(0,10,5,dtype=int)
nums = np.linspace(0,2,5)


2.0